# Generated by Django 3.0.6 on 2020-05-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Название категории RU')),
                ('name_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название категории UZ')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название категории EN')),
                ('cb_name', models.CharField(blank=True, max_length=50, verbose_name='Callback data')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('finished', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Profile')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Наименование товара RU')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='Наименование товара UZ')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Наименование товара EN')),
                ('description_ru', models.TextField(verbose_name='Описание товара RU')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание товара UZ')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание товара EN')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('type', models.CharField(blank=True, choices=[('pack', 'Упаковка'), ('bottle', 'Бутылка'), ('kilo', 'Развес')], max_length=20, null=True, verbose_name='Тип товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mybot.Category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybot.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Product')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.Profile')),
            ],
            options={
                'verbose_name': 'Позиция в корзине',
                'verbose_name_plural': 'Позиции в корзине',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ManyToManyField(to='mybot.CartItem')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mybot.Profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
