# Generated by Django 3.0.6 on 2020-05-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0002_cart_cartitem_category_order_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cb_name',
        ),
    ]
